[language.python]
command = "pyls"
install = [["pipenv", "install", "python-language-server"]]

[language.javascript]
command = "flow"
args = ["lsp"]
install = [["yarn", "global", "add", "flow-bin"]]

[language.html]
command = "html-languageserver"
args = ["--stdio"]
install = [["yarn", "global", "add", "vscode-html-languageserver-bin"]]
